# Generated by Django 5.1.4 on 2024-12-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelselection',
            name='parameters',
        ),
    ]
