# Generated by Django 5.1.4 on 2024-12-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_remove_modelselection_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('model_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='train.modelselection')),
            ],
        ),
    ]
